### ISSUE TITLE
Missing title and logo in integrations overview

### ISSUE THREAD

**Issue by ehn** [DSorlov/swemail#2]
The entry in the integrations overview has no title or logo.

<img width="310" alt="Screen Shot 2022-02-21 at 14 25 14" src="https://user-images.githubusercontent.com/179446/154900840-c482abd1-a3dc-446e-8bfd-65603e62354c.png">

**Comment by DSorlov** [comment]
Fixed in v1.0.2

**Comment by ehn** [comment]
> Fixed in v1.0.2

I have upgraded to 1.0.2, but it didn't fix the issue as far as I can tell.

**Comment by DSorlov** [comment]
Have you tried to click configure the integration and resaving? Reload page and it should be renamed?

**Comment by henrikbla** [comment]
In my setup (latest HA, running HAOS on RPi) the title and logo appeared only after removing the integration from Integrations page and readding it. Reconfigure and / or reload did not help.

That said, removing and readding is a rather painless operation :).

**Comment by DSorlov** [comment]
Thanks @henrikbla! My test environment isn't "clean" so could be that you are right.

@ehn Could you try and remove it and re-add it to see if it works for you?
Since this was a mistake only early installs will be affected so I was thinking of not doing a better fix than this.

**Comment by ehn** [comment]
> @ehn Could you try and remove it and re-add it to see if it works for you? Since this was a mistake only early installs will be affected so I was thinking of not doing a better fix than this.

Yes, I deleted and re-added it. Works fine now. Thanks!
